-- H2テスト用スキーマ定義: jOOQマイグレーション構造に完全対応
CREATE SCHEMA IF NOT EXISTS public;

-- publication_status ENUM型の代替（H2用）
DROP TABLE IF EXISTS public.publication_status_enum;
CREATE TABLE public.publication_status_enum (
    status VARCHAR(20) PRIMARY KEY
);
INSERT INTO public.publication_status_enum (status) VALUES ('UNPUBLISHED'), ('PUBLISHED');

-- authorsテーブル（V1マイグレーションに対応）
DROP TABLE IF EXISTS public.authors CASCADE;
CREATE TABLE public.authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- ビジネスルール制約: 生年月日は過去の日付（H2では簡略化）
    CHECK (birth_date < CURRENT_DATE)
);

-- authorsテーブルのインデックス
CREATE INDEX IF NOT EXISTS idx_authors_name ON public.authors(name);

-- booksテーブル（V2マイグレーションに対応）
DROP TABLE IF EXISTS public.books CASCADE;
CREATE TABLE public.books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    -- H2ではENUM型の代わりにVARCHAR + CHECK制約を使用
    publication_status VARCHAR(20) NOT NULL DEFAULT 'UNPUBLISHED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- ビジネスルール制約
    CHECK (price >= 0),
    CHECK (publication_status IN ('UNPUBLISHED', 'PUBLISHED'))
);

-- booksテーブルのインデックス
CREATE INDEX IF NOT EXISTS idx_books_title ON public.books(title);
CREATE INDEX IF NOT EXISTS idx_books_publication_status ON public.books(publication_status);
CREATE INDEX IF NOT EXISTS idx_books_price ON public.books(price);

-- book_authorsテーブル（V3マイグレーションに対応）
DROP TABLE IF EXISTS public.book_authors CASCADE;
CREATE TABLE public.book_authors (
    book_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- 複合主キー
    PRIMARY KEY (book_id, author_id),
    -- 外部キー制約
    FOREIGN KEY (book_id) REFERENCES public.books(id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES public.authors(id) ON DELETE CASCADE
);

-- book_authorsテーブルのインデックス
CREATE INDEX IF NOT EXISTS idx_book_authors_author_id ON public.book_authors(author_id);
CREATE INDEX IF NOT EXISTS idx_book_authors_book_id ON public.book_authors(book_id);

-- Flywayスキーマ履歴テーブル（jOOQが期待する）
DROP TABLE IF EXISTS public.flyway_schema_history;
CREATE TABLE public.flyway_schema_history (
    installed_rank INT NOT NULL,
    version VARCHAR(50),
    description VARCHAR(200) NOT NULL,
    type VARCHAR(20) NOT NULL,
    script VARCHAR(1000) NOT NULL,
    checksum INT,
    installed_by VARCHAR(100) NOT NULL,
    installed_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    execution_time INT NOT NULL,
    success BOOLEAN NOT NULL,
    PRIMARY KEY (installed_rank)
);